swagger: "2.0"
info:
  title: InnoAPI
  description: Backend for the ambev innovation game.
  version: 1.0.0
host: localhost:3000
basePath: /
schemes:
  - https
paths:
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in Markdown.
      produces:
        - application/json
      parameters:
        - in: path
          description: SigEduc registration number
          name: registration,
          required: true,
          type: integer
        - in: username
          description: username
          name: username
          required: true
          type: string
        - in: password
          description: password for the user 
          name: password
          required: true
          type: mixed
        - in: path
          description: lol
          name: userId,
          required: true,
          type: integer
        - in: path
          description: lol
          name: userId,
          required: true,
          type: integer
      responses:
        200:
          description: OK